# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Kamil Kubacki – the need for coding
email: natifweb@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I do Java and DevOPS on a daily bases
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kamilkubacki.com" # the base hostname & protocol for your site
permalink: /:year/:title
twitter_username: kamilkubacki
github_username: natif
linkedin_username: kamilkubacki
blog_url: /blog
public_speeches_url: /public-speeches

# Build settings
markdown: kramdown
